apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  labels:
    app: {{ include "myapp.fullname" . }}
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: 'default'
    receivers:
      - name: 'default'
        email_configs:
          - to: 'your-email@example.com'