apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-alertmanager
  labels:
    app: {{ .Release.Name }}-alertmanager
spec:
  selector:
    app: {{ .Release.Name }}-alertmanager
  ports:
  - port: 9093
    targetPort: 9093
    name: alertmanager