apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-alertmanager-config
  namespace: istio-system
  labels:
    app: alertmanager
type: Opaque
stringData:
  alertmanager.yaml: |-
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'remla12.notifs@gmail.com'
      smtp_auth_username: 'remla12.notifs@gmail.com'
      smtp_auth_password: "{{ .Values.smtp.encodedPassword | b64dec }}"
      smtp_require_tls: true

    route:
      receiver: 'gmail-alerts'
      group_by: ['alertname']
      group_wait: 10s
      repeat_interval: 30m

    receivers:
      - name: 'gmail-alerts'
        email_configs:
          - to: 'remla12.notifs@gmail.com'
            send_resolved: true