apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-alertmanager-config
  labels:
    app: {{ .Release.Name }}
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'remla12.notifs@gmail.com'
      smtp_auth_username: 'remla12.notifs@gmail.com'
      smtp_auth_password: '${SMTP_PASSWORD}'
      smtp_require_tls: true

    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'gmail-notifications'
      routes:
      - match:
          severity: critical
        receiver: 'gmail-notifications'
        continue: true

    receivers:
    - name: 'gmail-notifications'
      email_configs:
      - to: 'remla12.notifs@gmail.com'
        send_resolved: true 
