apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    app: myapp
spec:
  selector:
    app: app  # Match what your Pods use
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 5000