apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: MODEL_SERVICE_URL
              value: "http://{{ include "myapp.fullname" . }}-model:{{ .Values.model.port }}/predict"
            - name: NEW_DATA_URL
              value: "http://{{ include "myapp.fullname" . }}-model:{{ .Values.model.port }}/new_data"
            - name: VERSION_URL
              value: "http://{{ include "myapp.fullname" . }}-model:{{ .Values.model.port }}/version"
          volumeMounts:
            - name: shared-folder
              mountPath: /mnt/shared
      volumes:
        - name: shared-folder
          {{- if .Values.useHostPathSharedFolder }}
          hostPath:
            path: /mnt/shared
            type: Directory
          {{- else }}
          emptyDir: {}
          {{- end }}
