apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-app
  labels:
    app: {{ include "myapp.name" . }}-app
spec:
  selector:
    app: {{ include "myapp.name" . }}-app
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.containerPort }}