apiVersion: v1
kind: Service
metadata:
  name: sentiment-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: sentiment-app
  ports:
    - port: {{ .Values.app.servicePort }}
      targetPort: {{ .Values.app.port }}
  type: ClusterIP
