apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: 5000
