apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "myapp.fullname" . }}-destination
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ include "myapp.fullname" . }}-app.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: user 