apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "myapp.fullname" . }}-gateway
spec:
  selector:
    app: istio-ingress
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.ingress.host }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "myapp.fullname" . }}-app-vs
spec:
  hosts:
  - {{ .Values.ingress.host }}
  gateways:
  - {{ include "myapp.fullname" . }}-gateway
  http:
  - route:
    - destination:
        host: {{ include "myapp.fullname" . }}-app
        subset: v1
        port:
          number: {{ .Values.app.port }}
      weight: {{ .Values.istio.appTrafficSplit.v1Weight }}
    - destination:
        host: {{ include "myapp.fullname" . }}-app
        subset: v2
        port:
          number: {{ .Values.app.port }}
      weight: {{ .Values.istio.appTrafficSplit.v2Weight }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "myapp.fullname" . }}-model-dr
spec:
  host: {{ include "myapp.fullname" . }}-model
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "myapp.fullname" . }}-app-dr
spec:
  host: {{ include "myapp.fullname" . }}-app
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "myapp.fullname" . }}-model-vs
spec:
  hosts:
  - {{ include "myapp.fullname" . }}-model
  http:
  - match:
    - sourceLabels:
        app: {{ include "myapp.name" . }}-app
        version: v1
    route:
    - destination:
        host: {{ include "myapp.fullname" . }}-model
        subset: v1
  - match:
    - sourceLabels:
        app: {{ include "myapp.name" . }}-app
        version: v2
    route:
    - destination:
        host: {{ include "myapp.fullname" . }}-model
        subset: v2
  - route:
    - destination:
        host: {{ include "myapp.fullname" . }}-model
        subset: v1
      weight: {{ .Values.istio.modelTrafficSplit.v1Weight }}
    - destination:
        host: {{ include "myapp.fullname" . }}-model
        subset: v2
      weight: {{ .Values.istio.modelTrafficSplit.v2Weight }}