# Gateway (matches IngressGateway deployed during provisioning)
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "myapp.fullname" . }}-gateway
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.ingress.host }}
---
# Traffic split
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "myapp.fullname" . }}-app-vs
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "myapp.fullname" . }}-gateway
  http:
  - route:
    - destination:
        host: {{ include "myapp.fullname" . }}-app
        subset: v1
      weight: {{ .Values.istio.appTrafficSplit.v1Weight }}
    - destination:
        host: {{ include "myapp.fullname" . }}-app
        subset: v2
      weight: {{ .Values.istio.appTrafficSplit.v2Weight }}
---
# app subsets
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "myapp.fullname" . }}-app-dr
spec:
  host: {{ include "myapp.fullname" . }}-app
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
# model-service subsets
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "myapp.fullname" . }}-model-dr
spec:
  host: {{ include "myapp.fullname" . }}-model
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
# Routing app traffic to model-service according to v1/v2 subsets
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "myapp.fullname" . }}-model-vs
spec:
  hosts:
    - {{ include "myapp.fullname" . }}-model
  http:
    - match:
        - sourceLabels:
            app: {{ include "myapp.fullname" . }}-app
            version: v2
      route:
        - destination:
            host: {{ include "myapp.fullname" . }}-model
            subset: v2
    - route:  # default route (for v1 and others)
        - destination:
            host: {{ include "myapp.fullname" . }}-model
            subset: v1

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus
#   namespace: istio-system
# spec:
#   type: ClusterIP
#   ports:
#   - port: 9090
#     targetPort: 9090
#   selector:
#     app.kubernetes.io/name: prometheus