# templates/model-deployment.yaml (needs to be versioned like app)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-model-v1
  labels:
    app: {{ include "myapp.name" . }}-model
    version: v1
spec:
  replicas: {{ .Values.model.v1ReplicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}-model
      version: v1
  template:
    metadata:
      labels:
        app: {{ include "myapp.name" . }}-model
        version: v1
    spec:
      containers:
        - name: model
          image: "{{ .Values.model.image.repository }}:{{ .Values.model.image.v1Tag }}"
          ports:
            - containerPort: {{ .Values.model.containerPort }}
          env:
            - name: MODEL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "myapp.fullname" . }}-config
                  key: MODEL_HOST
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "myapp.fullname" . }}-secret
                  key: SMTP_PASSWORD
          {{- with .Values.model.env }}
          {{- range $key, $value := . }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          {{- end }}
            - name: MODEL_URL
              value: "https://github.com/remla25-team12/model-training/releases/download/v0.1.0/Classifier_Sentiment_Model.joblib"
            - name: VEC_URL
              value: "https://github.com/remla25-team12/model-training/releases/download/v0.1.0/c1_BoW_Sentiment_Model.pkl"
            - name: MODEL_CACHE_DIR
              value: {{ .Values.model.cachePath }}
            - name: FEEDBACK_FILE_PATH
              value: {{ .Values.model.feedbackPath }}/feedback_dump.tsv
          volumeMounts:
            - name: cache
              mountPath: {{ .Values.model.cachePath }}
            - name: feedback
              mountPath: {{ .Values.model.feedbackPath }}
            - name: shared-folder
              mountPath: /mnt/shared
      volumes:
        - name: cache
          emptyDir: {}
        - name: feedback
          emptyDir: {}
        - name: shared-folder
          {{- if .Values.useHostPathSharedFolder }}
          hostPath:
            path: /mnt/shared
            type: Directory
          {{- else }}
          emptyDir: {}
          {{- end }}
---

# templates/model-deployment.yaml (needs to be versioned like app)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-model-v2
  labels:
    app: {{ include "myapp.name" . }}-model
    version: v2
spec:
  replicas: {{ .Values.model.v2ReplicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}-model
      version: v2
  template:
    metadata:
      labels:
        app: {{ include "myapp.name" . }}-model
        version: v2
    spec:
      containers:
        - name: model
          image: "{{ .Values.model.image.repository }}:{{ .Values.model.image.v2Tag }}"
          ports:
            - containerPort: {{ .Values.model.containerPort }}
          env:
            - name: MODEL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "myapp.fullname" . }}-config
                  key: MODEL_HOST
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "myapp.fullname" . }}-secret
                  key: SMTP_PASSWORD
          {{- with .Values.model.env }}
          {{- range $key, $value := . }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          {{- end }}
            - name: MODEL_URL
              value: "https://github.com/remla25-team12/model-training/releases/download/v0.1.0/Classifier_Sentiment_Model.joblib"
            - name: VEC_URL
              value: "https://github.com/remla25-team12/model-training/releases/download/v0.1.0/c1_BoW_Sentiment_Model.pkl"
            - name: MODEL_CACHE_DIR
              value: {{ .Values.model.cachePath }}
            - name: FEEDBACK_FILE_PATH
              value: {{ .Values.model.feedbackPath }}/feedback_dump.tsv
          volumeMounts:
            - name: cache
              mountPath: {{ .Values.model.cachePath }}
            - name: feedback
              mountPath: {{ .Values.model.feedbackPath }}
            - name: shared-folder
              mountPath: /mnt/shared
      volumes:
        - name: cache
          emptyDir: {}
        - name: feedback
          emptyDir: {}
        - name: shared-folder
          {{- if .Values.useHostPathSharedFolder }}
          hostPath:
            path: /mnt/shared
            type: Directory
          {{- else }}
          emptyDir: {}
          {{- end }}
