apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-model-v1
  labels:
    app: {{ include "myapp.name" . }}-model
    version: v1
spec:
  selector:
    app: {{ include "myapp.name" . }}-model
    version: v1
  ports:
    - name: http
      port: {{ .Values.model.port }}
      targetPort: {{ .Values.model.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-model-v2
  labels:
    app: {{ include "myapp.name" . }}-model
    version: v2
spec:
  selector:
    app: {{ include "myapp.name" . }}-model
    version: v2
  ports:
    - name: http
      port: {{ .Values.model.port }}
      targetPort: {{ .Values.model.containerPort }}