apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: "{{ .Values.model.image.repository }}:{{ .Values.model.image.tag }}"
          ports:
            - containerPort: {{ .Values.model.port }}
          env:
            - name: MODEL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "myapp.fullname" . }}-config
                  key: MODEL_HOST
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "myapp.fullname" . }}-secret
                  key: SMTP_PASSWORD
          {{- with .Values.model.env }}
          {{- range $key, $value := . }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          {{- end }}
            - name: TRAINED_MODEL_VERSION
              value: v0.1.0 # Model version with Naive Bayes classifier
            - name: MODEL_CACHE_DIR
              value: {{ .Values.model.cachePath }}
            - name: FEEDBACK_FILE_PATH
              value: {{ .Values.model.feedbackPath }}/feedback_dump.tsv
          volumeMounts:
            - name: cache
              mountPath: {{ .Values.model.cachePath }}
            - name: feedback
              mountPath: {{ .Values.model.feedbackPath }}
            - name: shared-folder
              mountPath: /mnt/shared
      volumes:
        - name: cache
          emptyDir: {}
        - name: feedback
          emptyDir: {}
        - name: shared-folder
          {{- if .Values.useHostPathSharedFolder }}
          hostPath:
            path: /mnt/shared
            type: Directory
          {{- else }}
          emptyDir: {}
          {{- end }}
