apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-model
  labels:
    app: {{ include "myapp.name" . }}-model
spec:
  selector:
    app: {{ include "myapp.name" . }}-model
  ports:
    - name: http
      port: {{ .Values.model.port }}
      targetPort: {{ .Values.model.containerPort }}