apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-model
spec:
  selector:
    app: model
  ports:
    - protocol: TCP
      port: {{ .Values.model.port }}
      targetPort: {{ .Values.model.port }}
