apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
        - name: model-service
          image: {{ .Values.modelService.image }}
          ports:
            - containerPort: {{ .Values.modelService.port }}
          env:
            {{- range $key, $value := .Values.modelService.env }}
            - name: {{ $key }}
              value: {{ quote $value }}
            {{- end }}
          volumeMounts:
            - name: cache-volume
              mountPath: /app/cache
            - name: feedback-volume
              mountPath: /app/feedback
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: feedback-volume
          emptyDir: {}
