apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: ratelimit
    descriptors:
      - key: PATH
        value: "/predict"
        descriptors:
          - key: remote_address
            rate_limit:
              unit: minute
              requests_per_unit: {{ .Values.ratelimit.predictLimit }}
      - key: PATH
        rate_limit:
          unit: minute
          requests_per_unit: {{ .Values.ratelimit.globalLimit }}