apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}-app
  endpoints:
    - port: http
      path: /metrics
      interval: 1s

