services:
  app:
    image: ghcr.io/remla25-team12/app:${TAG_APP-latest}
    container_name: app
    volumes:
      - ../app:/app # assuming docker-compose is executed inside the operation folder, which is placed alongside the app folder
    ports:
      - 5000:5000 
    # depends-on:
    #   - model-service # to ensure the model loads before the web app
    restart: unless-stopped
    
  #model-service:
    #image: ghcr.io/remla25-team12/model-service:$(TAG_MODEL_SERVICE-latest)
    #container_name: model-service
    # environment:
    #   - ENV_VAR=<tbd>
    #   - Pass model url as env? 
    # volumes:
    #   - <tbd>
    #restart: unless-stopped

