version: '3.9'

services:
  app:
    image: ghcr.io/remla25-team12/app:latest
    container_name: app
    # environment:
    #   - ENV_VAR=<tbd>
    # volumes:
    #   - <tbd>
    ports:
      - 8080:8080
    restart: unless-stopped
    
  model-service:
    image: ghcr.io/remla25-team12/model-service:latest
    container_name: model-service
    # environment:
    #   - ENV_VAR=<tbd>
    #   - Pass model url as env? 
    # volumes:
    #   - <tbd>
    restart: unless-stopped

