version: '3.9'

services:
  app:
    image: ghcr.io/remla25-team12/app:${APP_TAG-latest}
    container_name: app
    env_file:
      - versions.env
    ports:
      - 8080:8080
    restart: unless-stopped
    
  model-service:
    image: ghcr.io/remla25-team12/model-service:${TAG_MODEL_SERVICE-latest}
    container_name: model-service
    env_file:
      - versions.env
    volumes:
      ### syntax: path/to/local/dir:path/to/docker/dir
    #  - ./:/root/
    # environment:
    #   - ENV_VAR=<tbd>
    #   - Pass model url as env? 
    restart: unless-stopped

