app:
  v1ReplicaCount: 1
  v2ReplicaCount: 1
  image:
    repository: ghcr.io/remla25-team12/app
    v1Tag: 0.5.7
    v2Tag: latest
    pullPolicy: Always
  containerPort: 5000
  port: 8080

model:
  v1ReplicaCount: 1
  v2ReplicaCount: 1
  image:
    repository: ghcr.io/remla25-team12/model-service
    tag: latest
    v1Tag: 1.1.6
    v2Tag: latest
    pullPolicy: Always
  port: 5000
  containerPort: 5000
  cachePath: /app/cache
  feedbackPath: /app/feedback

ingress:
  enabled: false
  host: myapp.local

monitoring:
  enabled: true

service:
  labels:
    app: myapp
  port:
    name: http
    port: 8080
    targetPort: 5000

istio:
  enabled: true
  appTrafficSplit:
    v1Weight: 50
    v2Weight: 50


useHostPathSharedFolder: true