namespace: sentiment-app

app:
  image: ghcr.io/remla25-team12/app:latest
  port: 8080
  servicePort: 80
  env:
    MODEL_SERVICE_URL: "http://model-service.sentiment-app.svc.cluster.local:5000/predict"
    NEW_DATA_URL: "http://model-service.sentiment-app.svc.cluster.local:5000/new_data"
    VERSION_URL: "http://model-service.sentiment-app.svc.cluster.local:5000/version"

modelService:
  image: ghcr.io/remla25-team12/model-service:latest
  port: 5000
  env:
    MODEL_URL: "https://github.com/remla25-team12/model-training/releases/download/v0.1.0/Classifier_Sentiment_Model.joblib"
    VEC_URL: "https://github.com/remla25-team12/model-training/releases/download/v0.1.0/c1_BoW_Sentiment_Model.pkl"
    MODEL_CACHE_DIR: "/app/cache"
    FEEDBACK_FILE_PATH: "/app/feedback/feedback_dump.tsv"

ingress:
  host: sentiment.local

monitoring:
  enabled: true

useHostPathSharedFolder: false