app:
  image:
    repository: ghcr.io/remla25-team12/app
    tag: latest
    pullPolicy: Always
  port: 8080

model:
  image:
    repository: ghcr.io/remla25-team12/model-service
    tag: latest
    pullPolicy: Always
  port: 5000
  cachePath: /app/cache
  feedbackPath: /app/feedback

ingress:
  enabled: true
  host: myapp.local

monitoring:
  enabled: true

service:
  labels:
    app: myapp
  port:
    name: http
    port: 5000
    targetPort: 5000

alertmanager:
  enabled: true

  alertmanagerSpec:

    secrets:
      - alertmanager-smtp-secret

    config:
      global:
        smtp_smarthost: "smtp.gmail.com:587"
        smtp_from:     "remla12.notifs@gmail.com"
        smtp_auth_username: "remla12.notifs@gmail.com"
        smtp_auth_password_file: "/etc/alertmanager/secrets/alertmanager-smtp-secret/SMTP_PASSWORD"

      route:
        receiver: "email"
        group_by: ["alertname", "instance"]
        group_wait: "30s"
        group_interval: "5m"
        repeat_interval: "1h"

      receivers:
        - name: "email"
          email_configs:
            - to: "remla12.notifs@gmail.com"
              send_resolved: true

useHostPathSharedFolder: false