app:
  image:
    repository: ghcr.io/remla25-team12/app
    tag: latest
    pullPolicy: Always
  port: 5000  # Changed to match container port

model:
  image:
    repository: ghcr.io/remla25-team12/model-service
    tag: latest
    pullPolicy: Always
  port: 5000
  cachePath: /app/cache
  feedbackPath: /app/feedback
  env:
    MODEL_SERVICE_PORT: "5000"

ingress:
  enabled: true
  host: myapp.local

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 1s
  grafana:
    enabled: true
    dashboards:
      enabled: true

service:
  labels:
    app: myapp
  port:
    name: http
    port: 5000
    targetPort: 5000

useHostPathSharedFolder: false

rateLimit:
  enabled: true
  maxTokens: 2
  tokensPerFill: 1
  fillInterval: 10s

istio:
  enabled: true
  gateway:
    name: my-gateway
    port: 80
  headers:
    userTest: "test-user"
