app:
  image:
    repository: ghcr.io/remla25-team12/app
    tag: latest
    pullPolicy: Always
  port: 8080  # <-- FIXED from 8080 to 5000

model:
  image:
    repository: ghcr.io/remla25-team12/model-service
    tag: latest
    pullPolicy: Always
  port: 5000
  cachePath: /app/cache
  feedbackPath: /app/feedback

ingress:
  enabled: true
  host: myapp.local

monitoring:
  enabled: true

service:
  labels:
    app: myapp
  port:
    name: http
    port: 5000          # <-- FIXED from 8080 to 5000
    targetPort: 5000    # <-- FIXED from 8080 to 5000

alertmanager:
  config:
    global:
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'our-app@gmail.com'
      smtp_auth_username: 'pipe.henry@gmail.com'
      smtp_auth_password_file: /etc/alertmanager/secrets/smtp_auth_password
    route:
      receiver: 'email-notifications'     # Correct singular form
    receivers:
      - name: 'email-notifications'
        email_configs:
          - to: 'pahenry@tudelft.nl'