app:
  v1ReplicaCount: 1
  v2ReplicaCount: 1
  image:
    repository: ghcr.io/remla25-team12/app
    v1Tag: 0.4.4
    v2Tag: latest
    pullPolicy: Always
  containerPort: 5000
  port: 8080

model:
  v1ReplicaCount: 1
  v2ReplicaCount: 1
  image:
    repository: ghcr.io/remla25-team12/model-service
    tag: latest
    v1Tag: 0.1.0
    v2Tag: latest
    pullPolicy: Always
  port: 5000
  containerPort: 5000
  cachePath: /app/cache
  feedbackPath: /app/feedback
  env:
    MODEL_SERVICE_PORT: "5000"

ingress:
  enabled: false
  host: myapp.local

monitoring:
  enabled: true

service:
  labels:
    app: myapp
  port:
    name: http
    port: 8080
    targetPort: 5000

istio:
  enabled: true
  modelTrafficSplit:
    v1Weight: 90
    v2Weight: 10

useHostPathSharedFolder: false