{
 "title": "Restaurant sentiment analysis",
 "tags": [ "myapp" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Model accuracy",
   "type": "gauge",
   "description": "% of correct predictions as reported by users",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_percentage_of_correct_predictions_gauge",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Breakdown of sentiment prediction feedback",
   "type": "piechart",
   "description": "More detailed overview of the model's current accuracy",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "correct_predictions_total", "legendFormat": "Correct predictions" },
    { "expr": "incorrect_predictions_total", "legendFormat": "Incorrect predictions" },
    { "expr": "reviews_submitted_total", "legendFormat": "Total reviews submitted" }
   ]
  },
  {
   "title": "Number of profile clicks for each team member",
   "type": "stat",
   "description": "Number of times each team member's profile was clicked within the chosen timeframe (range).",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "profile_clicks_total",
     "legendFormat": "{{member_name}} - v{{app_version}}"
    }
   ]
  },
  {
   "title": "Number of reviews by review length (number of characters)",
   "type": "bargauge",
   "description": "Number of reviews within the chosen timeframe (range))",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reviews" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(all_review_length_histogram_bucket[$__range])) by (le)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Review submission rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "rate(reviews_submitted_total[$__rate_interval])",
     "legendFormat": "Number of reviews"
    }
   ]
  },
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage_percent_gauge", "legendFormat": "Memory usage (%)" }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent_gauge", "legendFormat": "Memory usage (%)" }
   ]
  },
  {
   "title": "Comparison of Total User Clicks to Group Members’ LinkedIN Profiles for Different App Versions",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (app_version) (profile_clicks_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}