- name: Control-specific provisioning playbook
  hosts: ctrl
  become: yes
  gather_facts: yes

  tasks:
    # Step 13: Init cluster
    - name: Check if kubernetes is already initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: kube_config

    - name: Initialize cluster with kubeadm
      command: >
        kubeadm init
        --apiserver-advertise-address={{ api_server_advertised_address }}
        --node-name ctrl
        --pod-network-cidr=10.244.0.0/16
        --ignore-preflight-errors=NumCPU        
      when: not kube_config.stat.exists

    # Step 14: Setup kubectl
    - name: Create .kube directory in vagrant user's home directory
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0700'

    - name: Copy kubeconfig to vagrant user's .kube directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: '0600'
    
    - name: Copy kubeconfig from VM to host (fetch admin.conf)
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./
        flat: yes
      #when: not kube_config.stat.exists

    # Step 15: Create Pod network
    - name: Download Flannel config
      get_url:
        url: https://github.com/flannel-io/flannel/releases/download/v0.26.7/kube-flannel.yml
        dest: /tmp/kube-flannel.yml 

    - name: Add --iface=eth1 argument to Flannel container
      replace:
        path: /tmp/kube-flannel.yml
        regexp: 'args:\n( +- --ip-masq)'
        replace: 'args:\n        - --iface=eth1\n\1'

    - name: Apply Flannel network 
      command: kubectl apply -f /tmp/kube-flannel.yml
      become_user: vagrant
      # environment:
      #   KUBECONFIG: /home/vagrant/.kube/config

    # Step 16: Install Helm
    - name: Add Helm GPG key
      apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present

    - name: Add Helm apt repository
      apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present

    - name: Install Helm
      apt:
        name: helm
        state: present
        update_cache: yes

    # Step 17: Install helm-diff plugin
    - name: Install helm-diff plugin
      become_user: vagrant
      shell: helm plugin install https://github.com/databus23/helm-diff
      args:
        creates: ~/.local/share/helm/plugins/helm-diff

        
        


