---
# Pre-Step: Ensure required directories exist for Flannel
- name: Ensure /opt/cni/bin exists
  hosts: all
  become: yes

  tasks:
    - name: Create /opt/cni/bin directory
      file:
        path: /opt/cni/bin
        state: directory
        mode: '0755'

# Step 13
- name: Initialize Kubernetes Cluster
  hosts: ctrl
  become: yes
  gather_facts: yes


  tasks:

    - name: Check if kubernetes is initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: kube_config

    - name: Initialize Kubernetes with kubeadm
      command: >
        kubeadm init
        --apiserver-advertise-address={{ api_server_advertised_address }}
        --node-name ctrl
        --pod-network-cidr=10.244.0.0/16
        --ignore-preflight-errors=NumCPU        
      when: kube_config.stat.exists == false

    - name: Ensure kube config is accessible
      shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
      when: kube_config.stat.exists == false

# Step 14
- name: Setup kubectl
  hosts: all
  become: yes

  tasks:
    - name: Install kubectl
      apt:
        name: kubectl
        state: present
        update_cache: yes
    
    - name: Create .kube directory for vagrant
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0700'

    - name: Copy kubeconfig
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: '0600'
    - name: Copy kube config from VM to host (fetch admin.conf)
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./
        flat: yes
      when: kube_config.stat.exists == false

    # Step 15: Apply Flannel network
    - name: Download Flannel config
      get_url:
        url: https://github.com/flannel-io/flannel/releases/download/v0.26.7/kube-flannel.yml
        dest: /tmp/kube-flannel.yml 

    - name: Add --iface=eth1 argument to Flannel container
      replace:
        path: /tmp/kube-flannel.yml
        regexp: 'args:\n( +- --ip-masq)'
        replace: 'args:\n        - --iface=eth1\n\1'


    - name: Apply Flannel network
      command: kubectl apply -f /tmp/kube-flannel.yml

    # Step 16: Install Helm
    - name: Add Helm GPG key
      apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present

    - name: Add Helm apt repository
      apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present

    - name: Install Helm
      apt:
        name: helm
        state: present
        update_cache: yes

    # Step 17: Install helm-diff plugin
    - name: Install helm-diff plugin
      become: yes
      become_user: vagrant
      shell: helm plugin list | grep -q diff || helm plugin install https://github.com/databus23/helm-diff

        
        


