# ansible-playbook -u vagrant -i 192.168.56.100, provisioning/finalization.yml
- name: Finalize initialization of Kubernetes cluster
  hosts: all
  become: yes
  become_user: vagrant
  vars:
    dashboard_ingress_fixed_ip: 192.168.56.91
    venv_path: /opt/ansible-venv
    ansible_python_interpreter: "{{ venv_path }}/bin/python"
    dashboard_admin_yaml: | 
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: admin-user
        namespace: kubernetes-dashboard
      ---
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: admin-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: admin-user
        namespace: kubernetes-dashboard
    dashboard_ingress_yaml: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: dashboard-ingress
        namespace: kubernetes-dashboard
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          # nginx.ingress.kubernetes.io/secure-backends: "true"
          # nginx.ingress.kubernetes.io/ssl-redirect: "true"
          # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      spec:
        ingressClassName: nginx
        rules:
          - host: "dashboard.local"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: kubernetes-dashboard-kong-proxy
                      port:
                        number: 443


  tasks:
    # Step 20 - Install MetalLB
    - name: Download MetalLB yaml file
      get_url:
        url: https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
        dest: "/tmp/metallb-native.yaml"

    - name: Apply MetalLB CRDs
      kubernetes.core.k8s:
        state: present
        src: "/tmp/metallb-native.yaml"
     
    - name: Waiting for MetalLB controller pod to be ready
      kubernetes.core.k8s_info:
        kind: Pod
        wait: true
        namespace: metallb-system
        label_selectors:
          - app=metallb
          - component=controller
        wait_sleep: 5
        wait_timeout: 150
      
    - name: Configure IPAddressPool
      copy:
        dest: /tmp/metallb-pool.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            namespace: metallb-system
            name: default-pool
          spec:
            addresses:
              - 192.168.56.90-192.168.56.99

    - name: Apply IPAddressPool
      kubernetes.core.k8s:
        state: present
        src: "/tmp/metallb-pool.yaml"
     
    - name: Configure L2Advertisement
      copy:
        dest: /tmp/metallb-l2.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            namespace: metallb-system
            name: l2
          spec: {}

    - name: Apply L2Advertisement
      kubernetes.core.k8s:
        state: present
        src: "/tmp/metallb-l2.yaml"
      
    # Step 21: Install Nginx Ingress Controller
    - name: "Add Nginx Ingress repository"
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx
        state: present

    - name: "Install Nginx Ingress controller chart"
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: yes
        state: present
        values:
          controller:
            service:
              loadBalancerIP: "{{ dashboard_ingress_fixed_ip }}"

    # Step 22: Install Kubernetes Dashboard
    - name: "Add Kubernetes dashboard repository"
      kubernetes.core.helm_repository:
        name: "kubernetes-dashboard"
        repo_url: https://kubernetes.github.io/dashboard/
        state: present

    - name: "Install Kubernetes dashboard chart"
      kubernetes.core.helm:
        name: kubernetes-dashboard
        chart_ref: "kubernetes-dashboard/kubernetes-dashboard"
        release_namespace: kubernetes-dashboard 
        create_namespace: yes        
        state: present       

    - name: Create 'admin user config' (ServiceAccount & ClusterRoleBinding)
      copy:
        dest: /tmp/dashboard-admin.yaml
        content: "{{ dashboard_admin_yaml }}"
          
    - name: Apply admin user config
      kubernetes.core.k8s:
        state: present
        src: "/tmp/dashboard-admin.yaml"
      
    - name: Create dashboard Ingress
      copy:
        dest: /tmp/dashboard-ingress.yaml
        content: "{{ dashboard_ingress_yaml }}"

    - name: Waiting for dashboard ingress to be ready
      kubernetes.core.k8s_info:
        kind: Pod
        wait: true
        namespace: ingress-nginx
        label_selectors:
          - app.kubernetes.io/component=controller
        wait_sleep: 5
        wait_timeout: 150
      
    - name: Apply dashboard ingress
      kubernetes.core.k8s:
        state: present
        src: "/tmp/dashboard-ingress.yaml"
      
    - name: Generate dashboard admin token
      command: kubectl -n kubernetes-dashboard create token admin-user
      register: dashboard_token
      changed_when: false

    - name: Show dashboard login token and next steps
      debug:
        msg: 
          - "Kubernetes dashboard ready. Next steps:"
          - ">> Add the line '{{ dashboard_ingress_fixed_ip }} dashboard.local' to your host's hostfile"
          - ">> Go to https://dashboard.local and enter the following token: {{ dashboard_token.stdout }}"

    # Step 23: Install Istio
    - name: Determine cluster architecture (arm64 or amd64)
      ansible.builtin.set_fact:
        istio_arch: >-
          {{ 'arm64' if 'aarch64' in ansible_architecture else
            'amd64' if 'x86_64' in ansible_architecture else
            'unsupported' }}

    - name: Fail if architecture is unsupported by Istio
      ansible.builtin.fail:
        msg: "Unsupported system architecture: {{ arch_result.stdout }}. Istio only supports arm64 and amd64"
      when: istio_arch == 'unsupported'
      
    - name: Download Istio 1.25.2 for {{istio_arch}}
      ansible.builtin.get_url:
        url: "https://github.com/istio/istio/releases/download/1.25.2/istio-1.25.2-linux-{{ istio_arch }}.tar.gz"
        dest: /tmp/istio.tar.gz
        mode: '0644'
      become: true

    - name: Extract Istio
      ansible.builtin.unarchive:
        src: /tmp/istio.tar.gz
        dest: /home/vagrant/
        remote_src: yes
      become: true
      args:
        creates: /home/vagrant/istio-1.25.2/manifests

    - name: Add istioctl to PATH
      lineinfile:
        path: /home/vagrant/.bashrc
        line: 'export PATH=$PATH:/home/vagrant/istio-1.25.2/bin'
        insertafter: EOF
        state: present

    - name: Install Istio default profile (may take a while)
      shell: |
        export PATH=$PATH:/home/vagrant/istio-1.25.2/bin
        istioctl install --set profile=default -y
      register: istio_result

    - name: Confirm successful Istio installation
      debug:
        msg: 
          - "Result of Istio installation:"
          - "{{ istio_result.stdout_lines }}, {{ istio_result.stderr }},"



