- name: Install MetalLB
  hosts: all
  become: yes

  tasks:
    - name: Apply MetalLB CRDs
      command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml

    - name: Wait for MetalLB controller pod to be ready
      command: >
        kubectl wait -n metallb-system -l app=metallb,component=controller
        --for=condition=ready pod --timeout=60s

    - name: Configure IPAddressPool
      copy:
        dest: /tmp/metallb-pool.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            namespace: metallb-system
            name: default-pool
          spec:
            addresses:
              - 192.168.56.90-192.168.56.99

    - name: Apply IPAddressPool
      command: kubectl apply -f /tmp/metallb-pool.yaml

    - name: Configure L2Advertisement
      copy:
        dest: /tmp/metallb-l2.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            namespace: metallb-system
            name: l2
          spec: {}

    - name: Apply L2Advertisement
      command: kubectl apply -f /tmp/metallb-l2.yaml

- name: Install NGINX Ingress Controller
  hosts: all
  become: yes

  tasks:
    - name: Add ingress-nginx Helm repo
      command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

    - name: Update Helm repositories
      command: helm repo update

    - name: Check if ingress-nginx is already installed
      command: helm status ingress-nginx -n ingress-nginx
      register: nginx_status
      ignore_errors: yes

    - name: Install ingress-nginx via Helm
      command: >
        helm install ingress-nginx ingress-nginx/ingress-nginx
        --namespace ingress-nginx --create-namespace
        --set controller.service.loadBalancerIP=192.168.56.91
      when: nginx_status.rc != 0

- name: Install Kubernetes Dashboard
  hosts: all
  become: yes

  tasks:
    - name: Add dashboard Helm repo
      command: helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/

    - name: Update Helm repositories
      command: helm repo update

    - name: Check if kubernetes-dashboard is already installed
      command: helm status kubernetes-dashboard -n kubernetes-dashboard
      register: dashboard_status
      ignore_errors: yes

    - name: Install dashboard via Helm
      command: >
        helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard
        --namespace kubernetes-dashboard --create-namespace
      when: dashboard_status.rc != 0

    - name: Create admin user and ClusterRoleBinding
      copy:
        dest: /tmp/dashboard-admin.yaml
        content: |
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: admin-user
            namespace: kubernetes-dashboard
          ---
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: admin-user
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
          - kind: ServiceAccount
            name: admin-user
            namespace: kubernetes-dashboard

    - name: Apply admin user config
      command: kubectl apply -f /tmp/dashboard-admin.yaml

    - name: Create dashboard Ingress
      copy:
        dest: /tmp/dashboard-ingress.yaml
        content: |
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: dashboard-ingress
            namespace: kubernetes-dashboard
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              nginx.ingress.kubernetes.io/secure-backends: "true"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          spec:
            ingressClassName: nginx
            rules:
              - host: dashboard.local
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: kubernetes-dashboard-kong-proxy
                          port:
                            number: 8443

    - name: Apply dashboard ingress
      command: kubectl apply -f /tmp/dashboard-ingress.yaml

- name: Generate Kubernetes Dashboard token
  hosts: all
  become: yes
  tasks:
    - name: Create admin token
      command: kubectl -n kubernetes-dashboard create token admin-user
      register: dashboard_token

    - name: Show dashboard login token
      debug:
        msg: "Dashboard token: {{ dashboard_token.stdout }}"

- name: Install Istio
  hosts: all
  become: yes
  tasks:
    - name: Download Istio 1.25.2
      get_url:
        url: https://github.com/istio/istio/releases/download/1.25.2/istio-1.25.2-linux-amd64.tar.gz
        dest: /tmp/istio.tar.gz

    - name: Extract Istio
      unarchive:
        src: /tmp/istio.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Add istioctl to PATH
      lineinfile:
        path: /home/vagrant/.bashrc
        line: 'export PATH=$PATH:/opt/istio-1.25.2/bin'
        insertafter: EOF
      become_user: vagrant

    - name: Run istioctl install (demo profile)
      shell: |
        /opt/istio-1.25.2/bin/istioctl install --set profile=demo -y
      args:
        creates: /opt/istio-1.25.2/manifests
