# general.yaml
- hosts: all
  become: yes
  vars_files:
    - "{{ playbook_dir }}/keys/selin.pub"
  tasks:
    - name: Register SSH key of Selin
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ selin_key }}"

    - name: Disable SWAP
      ansible.builtin.shell: swapoff -a
      args:
        warn: false

    - name: Prevent a re-mount on the next boot by removing swap entries
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '.*swap.*' # I have no clue how to define the regex expression for this
        state: absent
        backrefs: yes

    - name: Register the automated load for future system boots using overlay and br_netfilter modules
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
          overlay
        owner: root
        group: root
        mode: '0644'

    - name: Add br_netfilter module
      community.general.modprobe:
        name: br_netfilter
        state: present