# general.yaml
- hosts: all
  become: yes
  vars_files:
    - "{{ playbook_dir }}/keys/selin.pub"
  tasks:
    - name: Register SSH key of Selin
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ selin_key }}"