- name: Setting up Kubernetes workers
  hosts: node-*
  become: yes
  gather_facts: no

  tasks:
    # Step 18
    - name: Generate join command from controller
      command: kubeadm token create --print-join-command
      delegate_to: ctrl
      register: join_command
      changed_when: false

    # Step 19
    - name: Join worker node to the cluster
      shell: "{{ join_command.stdout }} --ignore-preflight-errors=NumCPU"
      args:
        creates: /etc/kubernetes/kubelet.conf

